{
 "title": "ovs",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "ovs_up",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "targets": [
    { "expr": "ovs_up", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "ovs_info",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 5 },
   "targets": [
    { "expr": "ovs_info", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "ovs_exporter_build_info",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 10 },
   "targets": [
    { "expr": "ovs_exporter_build_info", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "ovs_interface",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 15 },
   "targets": [
    { "expr": "ovs_interface", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "ovs_vswitchd_pid",
   "type": "table",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "ovs_pid{component=\"ovs-vswitchd\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ovsdb_pid",
   "type": "table",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "ovs_pid{component=\"ovsdb-server\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ovs_log_file_size",
   "type": "table",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 29 },
   "targets": [
    { "expr": "ovs_log_file_size", "legendFormat": "__auto" }
   ]
  }
 ]
}